### ISSUE TITLE
Installation not working on python 3.8

### ISSUE THREAD

**Issue by kabirmdasraful** [impredicative/wrapdisc#1]
Thanks for your nice package. Is there any was to make this package install in python 3.8?

**Comment by impredicative** [comment]
I am sorry but there is just no incentive to support an old version of Python. Please update to the current version of Python.

**Comment by kabirmdasraful** [comment]
Thanks for your reply. I will integrate it with some of my existing code. Which has a lot of dependency on python 3.8. Thats why I was asking if it is possible to enable Python 3.8 also. Anyway thanks for a nice package.
